## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID             City Country  Max Temp Current Description      Lat  \
0        0    Cockburn Town      TC      78.8    scattered clouds  21.4612   
1        1           Outram      MY      77.0       broken clouds   1.2829   
2        2        Busselton      AU      64.0          light rain -33.6500   
3        6        Boa Vista      BR      86.0       broken clouds   2.8197   
4        7  Bambous Virieux      MU      78.8       broken clouds -20.3428   

        Lng                  Hotel Name  
0  -71.1419          Osprey Beach Hotel  
1  103.8379  Grand Copthorne Waterfront  
2  115.3333     Observatory Guest House  
3  -60.6733          Aipana Plaza Hotel  
4   57.7575              Casa Tia Villa

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [7]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Elizabeth City')
                                & (vacation_df['Hotel Name']=='Hampton Inn Elizabeth City')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Elizabeth City')
                              & (vacation_df['Hotel Name']=='Hampton Inn Elizabeth City')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Southern Pines')
                              & (vacation_df['Hotel Name']=='Holiday Inn Express & Suites Southern Pines-Pinehurst Area')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Charleston')
                                & (vacation_df['Hotel Name']=='The Mills House Wyndham Grand Hotel')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Havelock')
                                & (vacation_df['Hotel Name']=='Sherwood Motel')] 

In [139]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, stop1, stop2, stop3

(array([[ 36.2946, -76.2511]]),
 array([[ 35.174 , -79.3923]]),
 array([[ 32.7766, -79.9309]]),
 array([[ 34.8791, -76.9013]]))

In [132]:
# add the latitude/longitude
start=(36.2946, -76.2511)
end=(36.2946, -76.2511)
stop1=(35.174 , -79.3923)
stop2=(32.7766, -79.9309)
stop3=(34.8791, -76.9013)

In [133]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)
fig

Figure(layout=FigureLayout(height='420px'))

In [135]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID            City Country  Max Temp Current Description      Lat  \
0       58  Elizabeth City      US      62.6          few clouds  36.2946   
1      180  Southern Pines      US      63.0           clear sky  35.1740   
2      318      Charleston      US      77.0           clear sky  32.7766   
3      257        Havelock      US      64.4    scattered clouds  34.8791   

       Lng                                         Hotel Name  
0 -76.2511                         Hampton Inn Elizabeth City  
1 -79.3923  Holiday Inn Express & Suites Southern Pines-Pi...  
2 -79.9309                The Mills House Wyndham Grand Hotel  
3 -76.9013                                     Sherwood Motel

In [140]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
itinerary_locations = itinerary_df[["Lat", "Lng"]]

In [146]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(36.0, -76.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=itinerary_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))